"use strict";

var env = process.env;

module.exports = {
	TWILIO_AUTH_TOKEN: env.TWILIO_AUTH_TOKEN,
	TWILIO_DEFAULT_FROM: env.TWILIO_DEFAULT_FROM,
	TWILIO_SID: env.TWILIO_SID,
	TWILIO_PHONE_NUMBER_SID: env.TWILIO_PHONE_NUMBER_SID,
	PROTOCOL: env.PROTOCOL,
	HTTP_PORT: env.HTTP_PORT,
	SOCK_PORT: env.SOCK_PORT,
	URI: env.URI
};
